var searchData=
[
  ['_5f_5fattribute_5f_5f',['__attribute__',['../union____attribute____.html',1,'']]],
  ['_5f_5fcdc_5fbuf_5ft',['__CDC_BUF_T',['../struct_____c_d_c___b_u_f___t.html',1,'']]],
  ['_5f_5fser_5fbuf_5ft',['__SER_BUF_T',['../struct_____s_e_r___b_u_f___t.html',1,'']]],
  ['_5fbm',['_BM',['../struct___r_e_q_u_e_s_t___t_y_p_e_1_1___b_m.html',1,'_REQUEST_TYPE']]],
  ['_5fbm',['_BM',['../struct___b_m.html',1,'']]],
  ['_5fcdc_5fabstract_5fcontrol_5fmanagement_5fdescriptor',['_CDC_ABSTRACT_CONTROL_MANAGEMENT_DESCRIPTOR',['../struct___c_d_c___a_b_s_t_r_a_c_t___c_o_n_t_r_o_l___m_a_n_a_g_e_m_e_n_t___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fcdc_5fcall_5fmanagement_5fdescriptor',['_CDC_CALL_MANAGEMENT_DESCRIPTOR',['../struct___c_d_c___c_a_l_l___m_a_n_a_g_e_m_e_n_t___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fcdc_5fheader_5fdescriptor',['_CDC_HEADER_DESCRIPTOR',['../struct___c_d_c___h_e_a_d_e_r___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fcdc_5fline_5fcoding',['_CDC_LINE_CODING',['../struct___c_d_c___l_i_n_e___c_o_d_i_n_g.html',1,'']]],
  ['_5fcdc_5funion_5f1slave_5fdescriptor',['_CDC_UNION_1SLAVE_DESCRIPTOR',['../struct___c_d_c___u_n_i_o_n__1_s_l_a_v_e___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fcdc_5funion_5fdescriptor',['_CDC_UNION_DESCRIPTOR',['../struct___c_d_c___u_n_i_o_n___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5frequest_5ftype',['_REQUEST_TYPE',['../union___r_e_q_u_e_s_t___t_y_p_e.html',1,'']]],
  ['_5fusb_5fcommon_5fdescriptor',['_USB_COMMON_DESCRIPTOR',['../struct___u_s_b___c_o_m_m_o_n___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fusb_5fconfiguration_5fdescriptor',['_USB_CONFIGURATION_DESCRIPTOR',['../struct___u_s_b___c_o_n_f_i_g_u_r_a_t_i_o_n___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fusb_5fdevice_5fdescriptor',['_USB_DEVICE_DESCRIPTOR',['../struct___u_s_b___d_e_v_i_c_e___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fusb_5fdevice_5fqualifier_5fdescriptor',['_USB_DEVICE_QUALIFIER_DESCRIPTOR',['../struct___u_s_b___d_e_v_i_c_e___q_u_a_l_i_f_i_e_r___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fusb_5fendpoint_5fdescriptor',['_USB_ENDPOINT_DESCRIPTOR',['../struct___u_s_b___e_n_d_p_o_i_n_t___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fusb_5fep_5fdata',['_USB_EP_DATA',['../struct___u_s_b___e_p___d_a_t_a.html',1,'']]],
  ['_5fusb_5finterface_5fdescriptor',['_USB_INTERFACE_DESCRIPTOR',['../struct___u_s_b___i_n_t_e_r_f_a_c_e___d_e_s_c_r_i_p_t_o_r.html',1,'']]],
  ['_5fusb_5fsetup_5fpacket',['_USB_SETUP_PACKET',['../struct___u_s_b___s_e_t_u_p___p_a_c_k_e_t.html',1,'']]],
  ['_5fusb_5fstring_5fdescriptor',['_USB_STRING_DESCRIPTOR',['../struct___u_s_b___s_t_r_i_n_g___d_e_s_c_r_i_p_t_o_r.html',1,'']]]
];
